### ISSUE TITLE
panic: reflect: call of reflect.Value.Type on zero Value

### ISSUE THREAD

**Issue by mtojek** [elastic/go-ucfg#159]
Let's consider the following input:

```go
type Input struct {
	Vars []Variable `config:"vars" json:"vars,omitempty" yaml:"vars,omitempty"`
}

type Variable struct {
	Default     interface{} `config:"default" json:"default,omitempty" yaml:"default,omitempty"`
}
```

and such YAML document:

```yaml
vars:
  - default: []
```

Such YAML document fails unpacking:

```
--- FAIL: TestEmptyArray (0.00s)
panic: reflect: call of reflect.Value.Type on zero Value [recovered]
	panic: reflect: call of reflect.Value.Type on zero Value

goroutine 19 [running]:
testing.tRunner.func1(0xc000120100)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:874 +0x3a3
panic(0x13bcca0, 0xc0000c87c0)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
reflect.Value.Type(0x0, 0x0, 0x0, 0x14c1c40, 0x13b6f80)
	/usr/local/Cellar/go/1.13.4/libexec/src/reflect/value.go:1877 +0x166
github.com/elastic/go-ucfg.reifyGetField(0xc0000b36e0, 0xc0001061b0, 0x0, 0x0, 0x0, 0x0, 0x13b3060, 0x7, 0x13b6f80, 0xc0000af3b0, ...)
	/Users/marcin.tojek/go/src/github.com/elastic/go-ucfg/reify.go:346 +0x3b9
github.com/elastic/go-ucfg.reifyStruct(0xc0001061b0, 0x13cf5c0, 0xc0000af3a0, 0x199, 0xc0000b36e0, 0x0, 0x0)
	/Users/marcin.tojek/go/src/github.com/elastic/go-ucfg/reify.go:285 +0x93c
github.com/elastic/go-ucfg.reifyMergeValue(0xc0001061b0, 0x0, 0x0, 0x0, 0x0, 0x13cf5c0, 0xc0000af3a0, 0x199, 0x14be040, 0xc0000b36e0, ...)
	/Users/marcin.tojek/go/src/github.com/elastic/go-ucfg/reify.go:492 +0xe53
github.com/elastic/go-ucfg.reifyDoArray(0xc0001061b0, 0x0, 0x0, 0x0, 0x0, 0x1397c80, 0xc0000c87a0, 0x97, 0x14c1c40, 0x13cf5c0, ...)
	/Users/marcin.tojek/go/src/github.com/elastic/go-ucfg/reify.go:591 +0x308
github.com/elastic/go-ucfg.reifySliceMerge(0xc0001061b0, 0x0, 0x0, 0x0, 0x0, 0x1397c80, 0xc0000c8760, 0x197, 0x14c1c40, 0x1397c80, ...)
	/Users/marcin.tojek/go/src/github.com/elastic/go-ucfg/reify.go:577 +0x247
github.com/elastic/go-ucfg.reifyMergeValue(0xc0001061b0, 0x0, 0x0, 0x0, 0x0, 0x1397c80, 0xc0000c8760, 0x197, 0x14be040, 0xc0000b36b0, ...)
	/Users/marcin.tojek/go/src/github.com/elastic/go-ucfg/reify.go:498 +0xf33
github.com/elastic/go-ucfg.reifyGetField(0xc0000b34a0, 0xc0001061b0, 0x0, 0x0, 0x0, 0x0, 0x139ffc2, 0x4, 0x1397c80, 0xc0000c8760, ...)
	/Users/marcin.tojek/go/src/github.com/elastic/go-ucfg/reify.go:341 +0x2f3
github.com/elastic/go-ucfg.reifyStruct(0xc0001061b0, 0x13cf540, 0xc0000c8740, 0x199, 0xc0000b34a0, 0x0, 0x0)
	/Users/marcin.tojek/go/src/github.com/elastic/go-ucfg/reify.go:285 +0x93c
github.com/elastic/go-ucfg.reifyInto(0xc0001061b0, 0x138df20, 0xc0000c8740, 0x16, 0xc0000b34a0, 0x20, 0x13cf540)
	/Users/marcin.tojek/go/src/github.com/elastic/go-ucfg/reify.go:172 +0x40c
github.com/elastic/go-ucfg.(*Config).Unpack(0xc0000b34a0, 0x138df20, 0xc0000c8740, 0x0, 0x0, 0x0, 0xc0000b34a0, 0x0)
	/Users/marcin.tojek/go/src/github.com/elastic/go-ucfg/reify.go:155 +0x103
github.com/elastic/go-ucfg/yaml.TestEmptyArray(0xc000120100)
	/Users/marcin.tojek/go/src/github.com/elastic/go-ucfg/yaml/yaml_test.go:137 +0x131
testing.tRunner(0xc000120100, 0x14480b0)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:960 +0x350

Process finished with exit code 1
```

**Comment by mtojek** [comment]
Fix merged. Resolving.
